export const PATH_NAME = {
  HOME: "/",
  PRODUCTS: "/products",
  BLOGS: "/blogs",
  ABOUTUS: "/about-us",
  SIGNIN: "/sign-in",
  SIGNUP: "/sign-up",
  FORGOTPASSWORD: "/forgot-password",
  OURCOMMIT: "/our-commit",
  PRIVACYPOLICY: "/privacy-policy",
  ORDERINSTRUCTIONS: "/order-instructions",
  CONTACTINSTRUCTIONS: "/contact-instructions",
  OPERATINGPOLICY: "/operating-policy",
  ACCOUNT: "/account",
  PROFILE: "/account/profile",
  CHANGEPASSWORD: "/account/change-password",
  ORDERSHISTORY: "/orders-history",
  MYCART: "/my-cart",
  CREATEORDER: "/create-order",
};
